service: aws-lambda-practice
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
